### ISSUE TITLE
"m is not defined" External unpkg modules not working in latest Firefox

### ISSUE THREAD

**Issue by kevinfiol** [porsager/flems#104]
# Steps to reproduce

1. Open Firefox (latest version 93.0 as of writing this)
2. Navigate to https://flems.io/mithril
3. Attempt to use `m` in the .js tab.
4. See error in console: `m is not defined`

I tested this with https://flems.io/preact as well, but no luck. `preact is not defined`.

# System information
OS: Ubuntu 21.04
Browser: Firefox 93.0

EDIT: This actually may be related to #103 
EDIT2: For the record, these still work in Chromium 94

**Comment by porsager** [comment]
Fix also pushed to flems.io 🙂
