### ISSUE TITLE
auto compile failed 

### ISSUE THREAD

**Issue by npmrun** [porsager/flems#110]
[demo](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ZZjCANCAGYCWMeqA2qAHYCGAthGpgBbwNQEiwD2NiASwA8SEgDcABLCh1cAXgA6IAEa8AHsoB8impMmiJ02QuUqA5tt3791gwHox4nTWGOJW7pBgIS-CiAADKgAjADsIAC++LSMzOhYOHiEfAIQQglq6sB2KnSwANbmAE68AK40SKiSxcgA3HaSAO4kSPCs1QDMgQAO6g16NqwQJObsXb39dhgWOYP6LW0dkiEArH0DNpLDo+Mr61PzknmFJeWV1T0kNAWbkpG6kV7QcPB+NAEALKgAbFExIHoTBYGAAVskePxBPAWFEALqRIA)

## steps
1. open `.scss`
2. change `backround` value
preview not reload successfully，you must click refresh button

**Comment by porsager** [comment]
Can't repro. Reopen with reproducible case if possible ;)
