### ISSUE TITLE
Flems.io of the sample in README - URL points to next.flems.io

### ISSUE THREAD

**Issue by jimetevenard** [porsager/flems#114]
Hi !

Thanks a lot for this awsome tool ! 👍 

In your README, you wrote the folowing :

> ## Getting started
> Just load a single file [`flems.html`](https://flems.io/flems.html) in a script tag to get started. - [why should i load an .html file as a script tag?](#html-script-tag)
> ``` html
> <script src="https://flems.io/flems.html" type="text/javascript" charset="utf-8"></script>
> <script>
> // ...
> </script>
> ```
> 
> [Flems.io of the above](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8WAIwA+ADp0ABNIAqWMmGlLpAMRi4wUwQHpRkuoKRkAbiqQBeCaU3aQhvSdOOADodkaIWlcogMwCgBPaW8AI2QkZBUZJG5YAFdmPgZ4Ml5Q+FgMHJ1ddx0wWAAnMld4aTBi2GsQHHhXMFRdXToIAA94DBI7DHTdHu8wbDwoG2l4INcIWsRO3QArBlMAkrL4cdgsBmLIeFqE+BIAWgAOGzE9ItLyx2v1sWkpWVkAdzI6ONeMLy0ACkGWkI0mAzxe4PIlFQ0loYPB8OkjGY0IA5AxXK4MAswCjCHCES8eHwIHxUbgMMUSVFin8JFI6fA4olkl0wtwkEE8fSJHhaXURDZgTYABLQKDcaSvbjFKBIGwASjpdHlKPx4IAvgBdPEyAlQD4AayaMNBuoJLyREDJZHgWFKUFxaoJk2mqOxjrN5ukCRlqPqjWaugSdFcBoA5hgeLhdLgbXaKKrPRrNfj1YqjLp7rcQOrCPQmCx0FiqMQifx4Kwc3mQJbWJGwCWuLxy6xRMDXCCwbgdmGPsd4NxXNCAMwABlc7QA3GC5vBjgx9WG6NDYCTEMVp7qSM3jiQmMFoWAGHQwMdIKUSJv1fS6ABiQHKU2ybvFXvL6QAJnH7WkABZv5ushYBAZBhjg0L-gBYJsu0Z7bF80KjtISFfhO0ivmEDB-KOhA4ThGDDgArOm6o5pq6pAA)
> 

Fore some reason, the `src` attribute of the `<script>` tag, in the [Flems.io sample](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8WAIwA+ADp0ABNIAqWMmGlLpAMRi4wUwQHpRkuoKRkAbiqQBeCaU3aQhvSdOOADodkaIWlcogMwCgBPaW8AI2QkZBUZJG5YAFdmPgZ4Ml5Q+FgMHJ1ddx0wWAAnMld4aTBi2GsQHHhXMFRdXToIAA94DBI7DHTdHu8wbDwoG2l4INcIWsRO3QArBlMAkrL4cdgsBmLIeFqE+BIAWgAOGzE9ItLyx2v1sWkpWVkAdzI6ONeMLy0ACkGWkI0mAzxe4PIlFQ0loYPB8OkjGY0IA5AxXK4MAswCjCHCES8eHwIHxUbgMMUSVFin8JFI6fA4olkl0wtwkEE8fSJHhaXURDZgTYABLQKDcaSvbjFKBIGwASjpdHlKPx4IAvgBdPEyAlQD4AayaMNBuoJLyREDJZHgWFKUFxaoJk2mqOxjrN5ukCRlqPqjWaugSdFcBoA5hgeLhdLgbXaKKrPRrNfj1YqjLp7rcQOrCPQmCx0FiqMQifx4Kwc3mQJbWJGwCWuLxy6xRMDXCCwbgdmGPsd4NxXNCAMwABlc7QA3GC5vBjgx9WG6NDYCTEMVp7qSM3jiQmMFoWAGHQwMdIKUSJv1fS6ABiQHKU2ybvFXvL6QAJnH7WkABZv5ushYBAZBhjg0L-gBYJsu0Z7bF80KjtISFfhO0ivmEDB-KOhA4ThGDDgArOm6o5pq6pAA) points to https://`next`.flems.io/flems.html (unlike your docs, that points to https://flems.io/flems.html - without the `next` subdomain)

.

In addition, this version on `next`.flems.io seems to have a style break with Firefox (desktop or mobile) see the screenshot below : 
(In Chrome or Safari, it's fine)

[Reverting to `next.flems.io/flems.html`](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8WAIwA+ADp0ABNIAqWMmGlLpAMRi4wUwQHpRkuoKRkAbiqQBeCaU3aQhvSdOOADodkaIWlcogMwCgBPaW8AI2QkZBUZJG5YAFdmPgZ4Ml5Q+FgMHJ1ddx0wWAAnMld4aTBi2GsQHHhXMFRdXRI7DHTW9vYoG2l4INcIWsQAD3hdACsGUwCSsvg+2CwGYsh4WoT4EgBaAA4bMT0i0vLHE4WxaSlZWQB3Mjo4u4wvLQAKNu8wQmlgG9ugPIlFQ0loAMBkOkjGYoIA5AxXK4MJMwHDCBCobceHwIHx4bgMMU8VFiu8JFIKfA4olkvAMGFuEgghjKRI8OS6iIbL8bAAJaBQbjSO7cYpQJA2ACUFLoUrhmMBAF8ALoYmRYqCPADWTTB-w1WNuMIgBLI8CwpSg6MVWIGQ3hqJthqN0gS4vh9UazV0CTorm1AHMMDxcLpcObLRQFS7lSrMUqZUZdBczpxIDAEOk6FR0HtUAAmEQgJWEehMFjoFFUYg4-jwVglssgE2sENgGtcXj11iiX6uP4A3CrQOPHbwbiuUEAZgADK5RgBuAFjeA7BhawN0UGwPGIYrLjUkbs7EhMYKgsAMHM7SClEiHpWUugAYi+PgNsmHxVH2+kBfnUZpAAFkAw9ZCwCAyEDHBQVAsCAUZUZbxWZ5QVnaQMIAhdpB-MIGHeWdCCIoiMGnABWJMlRLFUlSAA) fixes the "flems in flems.io" sample

![Capture d’écran 2023-09-19 à 23 01 38](https://github.com/porsager/flems/assets/23314625/4809744d-8cd4-4dc7-a49f-05737d3de785)

Regards,
Jim

**Comment by porsager** [comment]
Oh right.. good catch - I'll get that fixed 👍

next.flems.io was a collaborative thing I never got around to finish up.. maybe some day..

And thanks a lot for the kind words :)
