### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by thmo** [porsager/flems#118]
Sorry if this is a dumb question, but is there a way to have the sidebar (to be able to add files, or get a perm link) for a self-hosted flems?

**Comment by porsager** [comment]
Not a dumb question at all.. That is only part of what I made for flems.io and not something included with flems the library itself. You'd have to code that yourself using the api.

**Comment by thmo** [comment]
Thanks. Just to clarify, are you intentionally not providing it as part of the library for self-hosting, or did it just not happen? What license is this code under?

**Comment by porsager** [comment]
It's a very opinionated solution and not as generic as the flems library so no, not something I'm gonna open source unless I stop keeping flems.io up.
