### ISSUE TITLE
Keyboard shortcuts regressions?

### ISSUE THREAD

**Issue by pygy** [porsager/flems#12]
I was used to use `cmd + l` to highlight the location bar, that no longer works (probably Sublime keybindings related). I have the  `cmd + l`,  `cmd + c` sequence hardwired in my fingers to export URLs (not just for Flems) and it is annoying to have it broken...

Also IIRC (but I'm not really sure) `CMD + /` used to toggle comments, not it shows/hides the console.

**Comment by porsager** [comment]
Hmm.. sounds odd about `cmd + l`. Which browser is that in? It works for me in safari, but not in chrome (I've never tried it in chrome though?).

wrt. `cmd + /`, i don't have that on my danish keyboard, but if I switch to US and try it, it toggles the browser status bar for me in safari, and nothing in chrome.

**Comment by pygy** [comment]
`cmd + l` used to work in both Firefox and Chrome too, now it selects a line, mimicking the behaviour of Sublime... I suppose that Safari catches the combo and doesn't let it through...

For `cmd + /` I may be misremembering. Github has the shortcut and so have Sublime and VSCode. I think it worked in Flems but I'm not sure.

I type in US/QWERTY because the keyboard shortcuts in editors are often designed with the US keyboard in mind and other layouts as an afterthought.

**Comment by porsager** [comment]
Thanks for the pointers 👍
