### ISSUE TITLE
[bug] primitives thrown don't show up in the error log

### ISSUE THREAD

**Issue by pygy** [porsager/flems#15]
Hello,

```JS
throw "hey!"
```

Gives this in the JS console:

```
TypeError: can't assign to properties of (new String("hey!")): not an object
r.flems.io:3:13655
uncaught exception: hey!
```

and [nothing](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5ihAE60A7gAIAOiEIwAngEJFbDiEw48+anAE16jZjzYBdVkA) in the Flems one.

**Comment by barneycarroll** [comment]
Flems are in principle a great way to assert and analyse failure cases — this confused me no end.

I second this motion!

**Comment by porsager** [comment]
Ah, yeah that's not good... I'll look at this right away...

**Comment by porsager** [comment]
Also deployed to flems.io now... Thanks for the report 😊

**Comment by pygy** [comment]
Perfect, thanks!
