### ISSUE TITLE
All Flems stop working after a while offline

### ISSUE THREAD

**Issue by pygy** [porsager/flems#16]
It's happenned to me twice to try things out in pre-loaded Flems while offline, and after a while (maybe an hour?), the iframe turns into the loading spinner and stays there forever.

There are network errors in the console but I didn't save them :-/

**Comment by porsager** [comment]
Does it load at all if you reload while offline?
Which browser?

I've had to make some special handling for Firefox, so it  It might be that, or that Firefox finally disabled support for html5 offline manifests.. I'll try to check up on that for starters.

**Comment by pygy** [comment]
Plain reloading doesn't work in either FF or Chrome.

Here's the Chrome log when reloading:

```
/#0=N4IgtglgJlA2C...snip...FTsnJIAA:1
Document was loaded from Application Cache with manifest https://flems.io

/cache.manifest?h=928c71d
/#0=N4Igt...snip...nJIAA:1 Application Cache Error event: Manifest fetch failed (6) https://flems.io/cache.manifest?h=928c71d

flems.js?h=be77f43:1
GET https://unpkg.com/mithril@1.1.5/mithril.js net::ERR_INTERNET_DISCONNECTED
(anonymous) @ flems.js?h=be77f43:1
request @ flems.js?h=be77f43:1
l @ flems.js?h=be77f43:1
t @ flems.js?h=be77f43:1
Qn @ flems.js?h=be77f43:1
qe @ flems.js?h=be77f43:1
oncreate @ app.js?h=ae4dabb:1
render @ app.js?h=ae4dabb:1
(anonymous) @ app.js?h=ae4dabb:1
(anonymous) @ app.js?h=ae4dabb:1
requestAnimationFrame (async)
(anonymous) @ app.js?h=ae4dabb:1
n @ app.js?h=ae4dabb:1
(anonymous) @ app.js?h=ae4dabb:1
Promise resolved (async)
loadExterns @ app.js?h=ae4dabb:1
(anonymous) @ app.js?h=ae4dabb:1
(anonymous) @ app.js?h=ae4dabb:1

/images/favicon-16x16.png?h=06f60f2:1
GET https://flems.io/images/favicon-16x16.png?h=06f60f2 net::ERR_INTERNET_DISCONNECTED

/favicon.ico?h=3c857ca:1
GET https://flems.io/favicon.ico?h=3c857ca net::ERR_INTERNET_DISCONNECTED
```

Oh wow, there's a lot more after pasting than what's displayed in the UI... I've reformted it a bit.

**Comment by porsager** [comment]
Hmm.. so maybe the mithril fetch is somehow interfering with the offline cache.. Loading a plain flems.io offline works for me, but loading existing flemses with deps seem a bit inconsistent.. I also discovered errors when loading dependencies are not shown anymore, so there's something else to fix as well :D

**Comment by porsager** [comment]
By the way.. Does reloading show flems and fail in the iframe, or does the entire page not show?

**Comment by pygy** [comment]
Flems loads, with the editor functional and a permanent spinner in the right pane.

**Comment by porsager** [comment]
I'll move this to https://github.com/porsager/flems.io/issues/4 as it's probably related to a flems.io specific implementation.
