### ISSUE TITLE
Unexpected auto indent

### ISSUE THREAD

**Issue by porsager** [porsager/flems#18]
Kindly reported by @osban

[Here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJGEyQF5JwADppJkgG4QYAd0SSAFAEp5APknIVatVn0ByACYR1tipavW7hAIwvJSkAAq8MT+hq6q7pI2tgBGAK7ExPQAxDLEvsoRkZLUUBhwcHr+af7h2ex+IADCADIAklUA0qFuaoZuALoqrCoqWPhYtHEM+va01HE4DPgxtPYAnhTSwYZsHCCYOHj41AWUNPSMzDxsHVRQEGgA1ggonFs8WBDEhABO0Ptxr+Q8JMQADoUAPRA4b-K4Acx2tCwQKeL3eUAAAl58KiAKxw55vaD4fj7Yjzf7cED49j3EnwnFQAC0EleMGwn2+eD+gMQILBkOhsKpiLpxAZ2BRaPwAAYgfTGf18VRCcS8GSOqwgA). When placing the cursor at the end of m('h1', "Test"),+ enter = OK. Placing it at the end of m('button#test', {+enter = it ends up underneath m( instead of there+1 indent. Placing at the end of class: "test",+enter = it ends up underneath m( instead of class.

**Comment by porsager** [comment]
Hi @osban .

What trips it up is apparently the fact that the children are indented, but simply being arguments to the `m()` call they don't make a new "indentation block".
I still think the indentation should work as you expected, and I write mithril views like that myself all the time, but if you [wrap them in an array](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJGEyQF5JwADppJkgG4QYAd0SSAFAEp5APknIVatVn0ByACYR1tiuctXrdwgEYXkpSAAKvDEAYYU7h42tgBGAK7ExPQAxDLEfsqqHlbUUBhwcHoBaQERWR7s-iAAwgAyAJLVANJhkZIAuobu7SqsKipY+Fi0cQz69rTUcTgM+DG09gCermmGbBwgmDh4+NQFlDT0jMw8bO1UUBBoANYIKJzbPFgQxIQATtAHcW-kPCTEAAdCgB6YGjAHXADmu1oWGBz1eHygAAFvPg0QBWeEvd7QfD8A7ERYA7ggAnsB6khG4qAAWgkbxg2C+Pzw-yBiFB4KhMLh1KR9OIjOwqPR+AADMCGUzBgSqESSXhye1WEA) it works as expected.

I'll take a closer look if this is easy to fix, but it's part of codemirrors smartIndent, so I'm not sure when I'll get around to it.

**Comment by osban** [comment]
I see. Yeah, I tend to leave out all the `[]`, as they clutter the view IMO. I'll use it as a workaround in the meantime :)
