### ISSUE TITLE
Very unusual indentation with unclosed parentheses

### ISSUE THREAD

**Issue by isiahmeadows** [porsager/flems#19]
For example, type this in JS mode:

```js
foo(() =>
)
```

When you get to this point, then inside the parentheses, hit enter.

```js
 foo(() =>
  //<- Where the indentation starts
 )
```

This is what's expected.

Now, try this:

```js
foo(bar(() =>
))
```

And inside the parentheses, hit enter.

```js
foo(bar(() =>
        //<- Where the indentation starts
))
```

This is a very odd inconsistency.

**Comment by porsager** [comment]
The funny thing is, that that's actually how codemirrors smartIndent works 👎 

I had previously fixed it by disabling smart indent if the line ended with `=>`, but then I reversed the parameters for my endsWith function and forgot to update the usage here 😓

**Comment by isiahmeadows** [comment]
Wonder if it's a bug in CodeMirror...
