### ISSUE TITLE
Lorem ipsum and a bad github link

### ISSUE THREAD

**Issue by pygy** [porsager/flems#2]
Hi @porsager,

you forgot to put some copy on the about page (the quickstart blurb would be a good start) and the github icon points to https://github.com/porsager/flems.io rather than https://github.com/porsager/flems

**Comment by porsager** [comment]
@barneycarroll wrote a very nice about text which is now online, and I also created a new repository for [flems.io](https://github.com/porsager/flems.io) to track flems.io specific issues. The about page is currently the readme in the flems.io repository as well. The link also works now that the new repository exists ;)

I still need to make a better intro to all the different features, but I hope to make that part of a page that can also be easily available to first time visitors. (I'll create an issue for that in the flems.io repo).
