### ISSUE TITLE
Fetch all code from editor

### ISSUE THREAD

**Issue by TeddyBones** [porsager/flems#20]
Hi,
I'm sorry if this is a stupid question, but is there any way to implement a function that fetches all the code in the current project? I thought you could do it with a custom compiler, but didn't succeed, and now I think I probably misunderstood. 

I just started to teach programming and html to young students in Norway (even though I'm not an expert) and would love to implement a function that saves the students project to our database as they type.  

Thanks,
Tormod

**Comment by porsager** [comment]
No not stupid question at all ! I wanted to get the public api for this right before exposing it in the documentation, but currently it's already possible to receive the entire state from each instance by doing like this [flems example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvSm2rAB2hgCc8AjDPxjkAvhXTZciAgCsEVOgybE8SuMQAEENBoxpqMTQF5NAMVhY4ACgAmtagFccDfP1q2AngEoAOmn8dPQMYfHpqQn0AcxhrPUYTAD5NDjjiDEZvbxBxSRw8fGo4BTZlZhl3L01gf01NQhgIKJJETQAWAAYOjgAPAG5-URyAXSooHQBrBBQ86XBLOCJScipHHnIZEmIOOEQAej2wBfwIWkPjkjJWYk8OOfkR0SA)

```
const instance = Flems(document.body)
instance.onchange(state => p(state)) // You can pull content from state or save directly into db from here
```

**Comment by TeddyBones** [comment]
Great! Thanks for making such an awesome web app. I'm surprised it hasn't gained more attention yet. I'm sure it will soon. :)

**Comment by porsager** [comment]
Thanks a lot! Really appreciated. 
Haven't really been doing much for promotion, but I'll hopefully find a bit more time for it soon.
