### ISSUE TITLE
Feature request: editable option on per file basis

### ISSUE THREAD

**Issue by TeddyBones** [porsager/flems#21]
I know there's already an option for making content editable or not, but it would be really nice if one could make certain files not editable while others are.

I'm using flems for education, so having static html while you can edit the css could save us teachers some headache. ;)

**Comment by porsager** [comment]
That seems like a great idea. I'll try to put that in tomorrow 😉

**Comment by TeddyBones** [comment]
Great! 😄 Thanks

**Comment by porsager** [comment]
Thanks for the pull request adding this feature ;)
