### ISSUE TITLE
Editable option can't be set after initial load

### ISSUE THREAD

**Issue by TeddyBones** [porsager/flems#22]
Can't get the editable option to work using the .set() function. 
Works when setting options on initial load though.

Tested the other options and it's only a problem with this one...

**Comment by porsager** [comment]
This is still using the undocumented `set` and `onchange` so I'll just close it for now, and make another issue to track a proper implementation for these use cases.

**Comment by TeddyBones** [comment]
Ok, I see. It's fixed in #24 anyway. :)

**Comment by porsager** [comment]
Hehe yeah, I'll happily take in things which can help in any way, just wanted to clean up the issues ;)

**Comment by TeddyBones** [comment]
I understand completely! Looking forward to the API :)
