### ISSUE TITLE
Feature idea: informative document title

### ISSUE THREAD

**Issue by foucist** [porsager/flems#35]
It's too hard to look for old unnamed flems in my history.  Zero indication of what they were about.

There's perhaps a few ways to make the document title informative for free:

1) Could include count of libraries, or include letters of each library in order of dependency? 
Example: [m/ms] for mithril & mithril-stream

2) Could include line count?  
Example: [h0,j50,c0]  (html lines = 0, js lines = 50, css lines = 0)

side idea: Could also include line count in the flems tabs themselves

**Comment by porsager** [comment]
That's a pretty good idea.. So have a summary title unless a custom name was given.. I'll definitely look into that at some point!

**Comment by porsager** [comment]
Moved to https://github.com/porsager/flems.io/issues/9
