### ISSUE TITLE
babel-standalone not work

### ISSUE THREAD

**Issue by futurist** [porsager/flems#36]
Please see [babel example in it's docs](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8AQgAiAeQDCAFQCaABQCiAAnZQAfAB06gtVp1YIDJPsHN4DZbCwMATpHgBeTSACu8EgFoAHC9PnLRmZnEAA3MggAdwAHblt4FyteficXSLIkeCxHJAhw2AhPdMysP21BAHpDY1MAI24kAE99cqQyUOUMkO53aPc-SrbQ02FPT2UAGW5jZQAhBlroZTHTMFhbMmj4ZTBbWBCceGiwVAqK1zpogGsAcwweXAqAAVqF6AqwCzokBiheCCeAHYMAAGUGeRYWDAAFgATBVXosoBgAFZgAYfdabeAjMbKWQ9WxWVyfbi4HZYraqCC2CDLTyrSnbeCNaIQEKIAAe8ARbygZToPDon2UNwg8AAshAwGAGGLlI5lAAKACUCvUyhcAAloH9lAB1OJQJAuADc2iQ3FgrmYfAwYvgihgtvgs0aAEkkEqAOQ9I7ub0qjBkOh0Gla6QSiYK0XiqUyuUQVXmnSYjZbfTKLPZrPlBENZp5vQgAC+hHoTBY6FRVGIQpSrFL5ZAQSrmFgMs49YgAnQpYAuiWgA)

I found it's not work in flems, is this a bug?

**Comment by porsager** [comment]
Interesting.. I'll have to look closer at it when I'm back at my computer, but it might be that Flems evaluates the script and removes it before Babel gets to it.. 

On a side note, was this just for the sake of the example, or have you seen that Flems has Babel built in?

**Comment by futurist** [comment]
Oh, I don't know flems has Babel built-in, just want run the code in babel's official docs but failed. Is there any way to use Flems' Babel instance?

**Comment by porsager** [comment]
With core just specify `compiler: 'babel'` on a file object. 

On flems.io you can select compiler on the small gear icon next to a file in the sidebar.
