### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by futurist** [porsager/flems#37]
I'm trying to build Flems, but throw below errors:

```
mac:flems pro$ yarn
yarn run v1.5.1
$ npm run build:main && npm run build:runtime && npm run build:standalone

> flems@1.1.14 build:main /Users/pro/github/flems
> node scripts/main

/bin/sh: svgcleaner: command not found
{ Error: Command failed: svgcleaner /Users/pro/github/flems/src/icons/logo.svg -c
/bin/sh: svgcleaner: command not found

    at error (/Users/pro/github/flems/node_modules/rollup/dist/rollup.js:168:15)
    at Object.error (/Users/pro/github/flems/node_modules/rollup/dist/rollup.js:17918:21)
    at /Users/pro/github/flems/node_modules/rollup/dist/rollup.js:17927:29
    at <anonymous>
  error: null,
  cmd: 'svgcleaner /Users/pro/github/flems/src/icons/logo.svg -c',
  file: '/bin/sh',

```

Anything I'm missed?

**Comment by porsager** [comment]
Sorry, I haven't added the setup for building — it requires the rust package [svgcleaner](https://github.com/RazrFalcon/svgcleaner) for now, but I plan to replace it with an npm packge such that a regular `npm install & npm run build` would do... I'll leave this issue open to track it, but let me know if you bump into anything after installing `svgcleaner`

**Comment by futurist** [comment]
Or can provide an option not to optimize the SVG file? Thus can provide a quick way to test the package.
