### ISSUE TITLE
Bug: once removed, a JS file with any given name cannot have its content persisted for the rest of the session 

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#38]
If you create foo.js, delete it, then create it again, none of its content will persist: it will not be executed and if you navigate away from the tab the content will have disappeared on return.

Refreshing the session will lose the content but fix the bug.

**Comment by porsager** [comment]
Ah, thanks a lot @barneycarroll ... also fixed a potential leak of the lazy loaded codemirror docs in the same go..
