### ISSUE TITLE
Add new files to the top of their stack

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#39]
Usually when adding a new file it will be to break out a piece of functionality the previous file depends on. When I create A, B, C, chances are B references C and A references B. With this in mind can we have it such that new files are inserted at the front of the list?

Also, moving files up and down is made difficult by the fact that the move down button collapses when disabled, causing the up button to change position depending on state. By rights the down button should leave an empty space to keep the up buttons in line.

**Comment by porsager** [comment]
Hi @barneycarroll 

Those are some very good points, which I've translated to code and deployed just now ;) I have kept the adding of css files to the end since I think (if using css) one might start with the coarse styling first, and then make it more fine grained if needing more css files...
