### ISSUE TITLE
Feature Request: CSS pre-processor support?

### ISSUE THREAD

**Issue by CreaturesInUnitards** [porsager/flems#40]
Yes, I know that as the inventor of BSS that this makes you want to stab me with a dull fork. But it wouldn't hurt in trying to broaden your audience, and as a completely random side effect it would make some of my own work _juuuuuuust_ a little easier :)

**Comment by porsager** [comment]
Haha, no not at all, I've been a huge stylus fan since its inception, and I've already laid the groundwork for adding it (you could actually already do it yourself using the compiler option on a .styl / .scss file).

I'll try to get stylus, less and sass added which i suppose are the big ones left?

**Comment by porsager** [comment]
Added in https://github.com/porsager/flems/commit/d7bdc15b88d110f00b80acb5ebbc314295c09cfe ;)
