### ISSUE TITLE
UI for external dependencies that have been edited

### ISSUE THREAD

**Issue by pygy** [porsager/flems#42]
We've discussed it in the past and I thought there was already an issue about it, but apparently there isn't... 

Flems supports editing foreign dependencies and stores the diff in its state.

It would be nice if

1) the name of files that have been edited were marked in some way (maybe italicize the name and add a `*`?)
2) there was a way to visualize the diff

(cc. @foucist who also suggested this in gitter)

**Comment by porsager** [comment]
Yeah, you're probably thinking of https://github.com/porsager/flems/issues/7 .

For starters before the patch view, it would be a great idea just to visualize that dependencies have been tampered with ! 🙂

**Comment by pygy** [comment]
I searched for `diff`, not `patch` :-)
