### ISSUE TITLE
Overflow tabs 

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#43]
It would be neat if we could allow the file tabs to scroll, as achieved for example with Github's mobile interface ribbon. When you consider how well embedded Flems work on mobile in eg http://meiosis.js.org/tutorial/10-deep-merge-mithril.htm, this would be a delicious cherry on the cake — and I don't even like cherries.

**Comment by porsager** [comment]
I think I fixed this at some point but forgot to match with this issue. I just checked the meiosis link on my iPhone SE, and I was able to scroll and reach each tab there :)
