### ISSUE TITLE
Safari Bug: editing embedded Flems jumps the page as if possessed by the devil

### ISSUE THREAD

**Issue by CreaturesInUnitards** [porsager/flems#44]
It's sporadic, but ƒ.e. editing the "Putting It All Together" example on [this page](http://meiosis.js.org/tutorial/05-stream-mithril.html) will make the whole page jump back up, oftentimes taking the active flem out of view. There's something about "least surprise" here, but I can't quite put my finger on it...

**Comment by porsager** [comment]
Thanks @CreaturesInUnitards.. This also removed an ugly unnecessary hack at the same time :P
