### ISSUE TITLE
Import default + others not working

### ISSUE THREAD

**Issue by osban** [porsager/flems#45]
As discussed on the Mithril channel, something like `import modal, {status1, status2} from './modal'` doesn't work. You suggested it was a regex issue, and after studying it, it looks like the `isModuleRegex.test()` is returning `undefined`. I could make it work by adding `|\w` just before `(?!type)`. Not sure if that's correct, though.

**Comment by porsager** [comment]
Hi @osban. So sorry I didn't get around to answer you on gitter.. It's been really busy around here, but I did manage to fix it with this commit : https://github.com/porsager/flems/commit/7a1b8a83a08a70da18d2480b5df5393fa7dc4178

I think \w would bring some false positives, but the above is better and fixes the issue, I just haven't gotten around to deploying to flems.io yet. 

Hopefully tonight or tomorrow 😉 

Thanks for the help 😉

**Comment by porsager** [comment]
Ok finally got around to deploying to flems.io as well ;) sorry for the wait

**Comment by osban** [comment]
Great! No worries, I only created the issue because I thought you might've forgotten ;)
