### ISSUE TITLE
SCSS highlighting doesn't work correctly

### ISSUE THREAD

**Issue by TeddyBones** [porsager/flems#46]
There's something off with the way SCSS highlighting works. Perfectly valid IDs light up in red. 

https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ZZjCANCAGYCWMeqA2qAHYCGAthGpgBbwNQEiwD2NiASxABffLUbN0GAFZ5CfARCHpR4kPSYssOeT36D4LAMSIw8AATAAOjQu2R3PgwAOZCACcW2XN0gwEEn4KEABGVFDRAF0RIA

**Comment by porsager** [comment]
Ah you're right - it doesn't have the css highlighter assigned. Thanks.

The types and identification of them is a bit messy after I added more, so I'll make a small cleanup while fixing this at the same time :)
