### ISSUE TITLE
Can't scroll the display area after resizing the panes.

### ISSUE THREAD

**Issue by pygy** [porsager/flems#47]
If you resize the editor/display [panes by dragging the separation](https://flems.io/#0=N4IgtglgJlA2CmIBcBmALAOhQRgDQgDMIEBnZAbVADsBDMRJEDACwBcxYR8BjAeytbwByECAC+uanQbgaAa3gBaMP1bMSGAFZkeqoaxEEArlW6sI-AARh58ALKr1ACgCe8GgCcAlMAA6VS0s+KhJWSyhLAF5LKngAd0sAERpBJy9-QKgMEnhWBwFmJwAGdIDw7Nzk1OxSzIrWADEjWFgATXcPVw7aywQwlQKSKMtyAF0Mywhhov9ZsrjmYnhLJyyAc1ymlvbPNIAeSzdPSwBqS2xLADJLycs9tCKSvzLA4NDrYfXc-LU0idf+O8YJ8MBtWFV4H8XtZHCRyGBRsMBmo4QjLAAfdEjcbQ7jMeDcBQRaJfcE0FxpSwAQki0SKVxupOSFK81NplgAbP8YYN4aMMAAHIwkQrAGC4IL4wnwKASqApeBIGLxJIK1ag3IAFQg9DSXjEpW5WRyZNSTLVXhONQA3JMTicJmIJh5ckYPAFkep-GIuCAcggzBYQiJsABOJDYcSSEC0egiLQ6EDBQTCRhzPo8lFI2w-ZwAJiK2AAHIaqHM3mF5S4htFyL4QLAjPWJfWbM3LK34O365ou1wOyAAG59lt+mjdkBQCD1nH+YymcxWAU0KDalqrcms56BF2sN0BACCHg85IwNAFAtgFKozVgEuACCoazUSo3LhOHK8AFIAOwGjA2AKTgAB6RAAfGATj1hgVb1l4pROmWVBgABvAmKwqy8NwRj0AIGAAEa8FALj3oOEDxGk25BICYQ0C0zI1tiGDBNwKRnheV5OGMEqeiQPQVpKBJEsM5BFLgYkSeJUlFDigR0bADEYAQvAeAAojQeKrFA4FUZk5KfFk8qCBqZIsty3IQAQKwwMxUpElu3KvHZMrkG+H7fj+iInNE2DcohgQGhMGS7vuIzcrxAHnk4TiejxECsuBYXQoEkH1lOg7kKELgIJEADk3AIJ4SCEWouXjP2jmBNYUFMLB-apSA+HtpAVrwS2yVVQ1qEFM25DLquxCwDFjiifyRnwCZzJ6rglUpY4kVAVpcrxVEYEjF1dWSLNVVZQgSrAPhGlyGsHhoVQUAAMK8LAKlKjZeJCTKAD8A4nfAQj1kg9YqTQT59hI22BPwBUQISSooXEEBqAerCsJ09YPdKUDtqBa28fCECjOQU78ojwnRFS6OQFjOO2Y9UA9FVVUSOEhkU6OA6jF4TOVV4M3Qkz7NU1WGiAdF4qTAlaM1elmWsNl8B5QVHTFbwpXlXKsoDgOEp4y5mNteFIsQBlu2S-lhUeLL8sTpqct0SrljyYpRCwIInTaWBWRqxTGCPs+zCloEOJiIFSG+nwYACksHjIDeLQSFIcaMMxJCJsm+giAAVJYVE2B4awQFQSBFNa-VTk+OfWt6-gwfpVEEDdKRKggBCsMXZT4hAaxsEqKBFAKwEN4EkNQC+ljt53DeId1aipxMle8NXtf1xMvcvtgi8d13JdUMwaDj2U0tFSVzDD-4AAC9BTjQlgkNwLpCFb50rDYwGKPPzBKovDydw5ZSj8wm9U4-SpFq-K8yiIUQofY+EBT7n0vgEX6EQYo0Hvr-SwRYfzL3foET+38qqII5IPQBAVV5HxlOAs+F93rQJvnAhB0B+4cg5KgzBGDdKWEQWgAsQ9HQELARA0hV8YG33gQ-ahT9LBoAAKz0Koow7kiC8zYGXt3SwwD-C+n9ASRcwZGCyJzuIUY+BYBZzkGQJAlAYzSBEJANQHhiC+jdJwRgbBWAChIEgAA9C4kwApjrMV4GAFxFjmBWNgAfbAGAQkcj8VDAJxAEy+nFgKGQkCIACgMGIUYYggA), the display area becomes unscrollable (unless refreshed using the circular arrow button).

**Comment by TeddyBones** [comment]
This happens for me in safari, while everything works in chrome.

**Comment by porsager** [comment]
I think the only options is reloading the iframe on drag end (but only in safari)? What do you think?

I can't figure out if it's best to do that, or leave it as is now, and then people will most likely do a refresh themselves?

**Comment by pygy** [comment]
I'd leave it as it is right now.

The refresh may not be welcome while testing something responsive that doesn't need scrolling.

**Comment by porsager** [comment]
If I had the time I'd make a small repro and create a bug with webkit, but I don't think that'll happen any time soon, and since I don't seem to be able to find a workaround I'll close this issue for now :-(
