### ISSUE TITLE
In mobile mode with the editor collapsed, the "show editor" bar is drawn over the content, rather than above it.

### ISSUE THREAD

**Issue by pygy** [porsager/flems#48]
[This Flems is affected](https://flems.io/#0=N4IgtglgJlA2CmIBcAGAdAZgGwBoQDMIEBnZAbVADsBDMRJENACwBcxYQ8BjAe0pfj9kIEAF8cVWvXDUA1vAC0YPiybE0AK1LcVglsPwBXSlxYQ+AAjBz4AWRVqAFAE941AE4BKYAB1KFi15KYhYLKAsAXgtKeAB3CwARagFHTz8AqDRieBZ7fiZHFDT-MKycpJSARmKMspYAMUNYWABNN3cXdpqLBFDlfOJIizIAXXSLCCGUPxmS2KYieAtHTIBzHMbmto9UgB4LVw8LAGoLSosAMguJi12AFhQi3xKAoJCrIbWcvNVU8de+O8YJ80OsWBV4H8XlYHMQyGARkN+qo4QiLAAfdHDMbQrhMeBceThKJfcHUZypCwAQgiURQl2upKSFM81NpFiw-xhA3hIzQAAdDMQCsAYDhAvjCfAoOKoMl4EhonFEvKVqCcgAVCB0VKeUTFLmZbJklJM1WeY7VADcE2Ox3GonG7hyhnc-mRaj8ok4IGyCFM5mCwkqAE4kJUxBIQDQ6MJNNoQEEBEIGLNetyUUibD8nAAmFCVAAcBsoszeoTlzkGUTIPhAsEMdfFdesTYsLfgbbrGk7nHbIAAbr3m77qF2QFAIHWcX4jCYzJZ+dQoFrmityazngFnSxXf4AILudzktDUfn82AUyhNWDi4AISirVSK9fOY5YTwAUgA7Pq0NZ+UcAAPCIAD4wEcOs0ErOtPGKR1S0oMB-x4YwWBWHguEMOh+DQAAjHgoGcO8BwgOJUi3QJAVCahmmZatsTQIIuGSU9z0vRxRnFD1iG6csJQJIkhjIFAcFE8SxMklAcQCWjYHotB8B4dwAFFqDxFYoDAyiMnJT5MjlAR1TJFkuS5CB8GWGAmMlIlNy5V5bOlMhX3fL9v0RY4okqLkEICfVxnSHc92GLkeP-M9HEcD1uIgVkwNC6EAggutJwHMgQmcBAIgAci4BAPCQAjVBysY+wcgIrEgxgYL7FKQDwttIEtODmySyr6pQ-ImzIJcVyIWBoocES+UM+BjOZXUcAq5KHAiwDNNlOLIlA4ZOtqiQZsqzKEEVYA8PU2RVncVDKCgABhHhYGUxVrLxQTpQAfn7Y74EEOskDrZTqEfXtxC2gI+HyiBCUVZDYggVR9xYFgOjre6pSgNsQNWnj4QgEYyEnPkEaEqIqTRyBMexmyHqgbpKsq8QwgM8mR37EZPEZirPGm6FGbZynK3UACorFCZ4tR6q0oylgsvgXL8vaIqeBKsrZRlft+3FXHnIx1qwuFiB0p2iW8oK9wZbl8cNVl2jlYsOSFMIWABA6LTQMyVXybQB8nyYEsAhxUQAsQn1eDAflFncZBr2acRJFjBgmOIBMkz0YQACoLEo6x3FWCBKFQK0+snR9s69PxoL0yj8Gu5JFQQfAWCtcZ8QgVZWEVDAUH5IDa7maBnwsFu247hCutUFPxjLngK6rmvxghqBn0qOfW-bwvKCYO5h5KKXCuKph+78AABOhJ2oCxiC4Z1BEts7lmsICFGn7u54eNv7JKQemDXym76YRVC0fxeSgQhCe8D4QCPifM+-gfrhGitQG+n9v7fgXs-AIr936VTgRyXuf9-JL33tKEBx9T5vQgZfaBsCu5fw5FgRBqCUE6QsOgu4+Y+4OhwcA0BhDz6QKvjA2+5DFR3AAKzUMorQrk6DcyVAXh3bBlAEI+j9ASBcQYGASNQGIEYeBYCZ1kKQJAFBoxSGEJAVQ7giA+ldBwBgrAWD8mIEgAA9PY4w-IjpMR4GAexximCmNgLvSoaB-FYE8ZDbxRB4w+jFvyaQYCID8n0KIEYoggA).

**Comment by porsager** [comment]
Nice one :) thx @pygy
