### ISSUE TITLE
console.trace() causes an exception because flems' monkey-patch always expects arguments

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#50]
[As seen here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbrQgATAAQAKMAFc01YhHoy4hWgHc5ASmAAdNDJlC4tWPmIAnDNRgGTrfQcog4MWKvVoEPABMiAAsbBwgmDh4+NRwAjT0jMw8bAC6rEA), Flems throws when it complains that

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
```

...upon calling `console.trace()`. It expects an argument, but none should be necessary.

**Comment by porsager** [comment]
Fixed in https://github.com/porsager/flems/commit/6e8bd1870bf0a3248083478588e5b10e0b67656c
