### ISSUE TITLE
Flems is Awesome

### ISSUE THREAD

**Issue by mike-ward** [porsager/flems#51]
Yeah, I know this is not really an issue. Just wanted to say thanks for writing it.

Like Mithril, it hits that sweet spot of usability and completeness.

**Comment by porsager** [comment]
😄 Thank you so much @mike-ward !! That's really nice to hear...

Which reminds me I forgot to mention you can set `theme: 'default'` now to get the light theme as requested in https://github.com/porsager/flems.io/issues/10 ;)
