### ISSUE TITLE
Convert code to flems link

### ISSUE THREAD

**Issue by mike-ward** [porsager/flems#53]
I'm thinking for blog posts that it might be better to show a code block normally using `<pre><code>...` and having a link to `flems.io`. Obviously, I can go to `flems.io`, copy/paste code and then copy the link, but that's a bit tedious.

An additional API. similar to `Flems(element, options)` that builds a link would be helpful.

**Comment by porsager** [comment]
Ah, that's a good idea.. Perhaps a `flems.io` package would be better suited for that though?
Until then you can easily build it yourself [like this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgwAIIATAXgB1wsLHAHtiGAE4BzGMX4gARlAxoA1gIB8AGQhqxtdmCFwWAegwbKIODFjViEegkQgADIgBMAdhABfCujYuC74AFYIVHQMTMR4RjDCRBIwYOw87ADkJMQADnCIpqbxiY6mAMSuPBnsANTsWgBaAMrEErpS+HRYOclwcAAqtACiaHRcMFwAqgBKAJIAwrTd9DEAFHxo7FvsAFJNAPIAcvhwre0QYACeq8Ab29uQsPnsqHf325g4iJlhcBkUb3e7CijAY3wyAHcMMQMoDtr4ALpw3wASi2bxRVi6OWgMAkeAUGAUtisNjsDiceAAjIgqQAOPwBECfYIEah9LH0UGxFx+BFUKC6VTOVDMoJ4KAALwAtKc2mgpFYAK4ScgubJ5AqmJVoHKqDpdUxS2VnBUAASp+AALNajRAFHAjTK5e1flZiJccqy4NQ2jlYojfEA)
```
'https://flems.io/#0=' + LZString.compressToEncodedURIComponent(JSON.stringify(state))
```

**Comment by porsager** [comment]
Would also love to hear your thoughts on why you think it's better to show a code block?

**Comment by mike-ward** [comment]
I find the page jumps around when a bit. See http://mike-ward.net/2018/05/09/mithril-rising/. I ended up adding a `scroll(0,0)` to force it to the top. Seems to have something to do with the ajax call in one of my examples.

I got three down votes on EchoJS for my article. I've never seen that before. I think it must be something to do with the code sample. This is essentially an update to a previous article that got lots of upvotes and downs. I might be reading to much into it, but then again...

The narrow format of my blog does not play well with the side-by-side code output view.

Question about `'https://flems.io/#0=' + LZString.compressToEncodedURIComponent(JSON.stringify(state))`

How do I include packages?

**Comment by porsager** [comment]
`state` in that example is the same state as you provide to `Flems(domElement, state)`, so something like: 
```
'https://flems.io/#0=' + LZString.compressToEncodedURIComponent(JSON.stringify({
  files: [{
    name: '.js',
    content: 'm.render(document.body, m("h1", "hello"))'
  }],
  links: [{
    url: 'https://unpkg.com/mithril',
    type: 'script'
  }]
}))
```

**Comment by mike-ward** [comment]
Oh, I see. That's perfectly acceptable. API not needed. Might be worth documenting.

**Comment by porsager** [comment]
Whoa.. yeah, weird that it starts out at the middle of the page..

Also weird with the downvotes.. It's a pity there's no comments about why...

On a side note you'll be able to specify layout in the next update to force either side by side or stacked instead of auto (as currently where it adjusts depending on container ratio).

**Comment by porsager** [comment]
Yeah, I'll need to document and write about all of this, but it's so much more fun building it :D I want to get persistence on flems.io finished first, and then I might be able to pull myself together for it ;)

**Comment by mike-ward** [comment]
OK, update the page to show code blocks with links. Kind of dull but less noisy I suppose.

**Comment by mike-ward** [comment]
Another thought (maybe a separate issue), maybe Flems could be smart about loading npm packages from import statements?

```
import m from 'mithril'
```

**Comment by porsager** [comment]
Yeah, that actually works for packages that has `"module": "target"` in their package json ;) Mithril just isn't compiled to esm :-(

[Here's a sample](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEAIzlhptLHIDkCuHA0AdNAaz5pTACYxpACjO1qAVxwN8C2mYCeFA3LlYrGwgBGDTkAakUAA28fRWpFKHsYaJ84gHdCCEZkuWIMOWoRS2ywMDlxCQxqYmzieXsJCUtqDDgktBi5CTkAJmiIik0ACQgcwksYDQBKA0nKEFbYKoh6BB4ATkQAdjYOEEwcPHxqHTmhRmYeNgBdKigINABrVdQ9rjwsTMJpaDn7aXIeCRiBI4IgAPRg+xoCQPADmRzUYI+xC+0AAAoF8JiAGxIz7fKD4fhzYjuRp4ODUb4SUSsK6sIA)

**Comment by tormodvm** [comment]
The sample you posted with "import" works in safari and chrome, but not in firefox. Hm... That's strange...

**Comment by mike-ward** [comment]
This [example](https://flems.io/#0=N4IgtglgJlA2CmIBcBWFAaEBDArgFwHsAJeCAcwAs9k8AnHeTAMwgQGdkBtUAOyzERIQAOgBWHTAGMCPPPFnIQ0nmzwACMASjxYagLxrgAHR5q1ARwa0AnkjUBye+hNm6WSQGs2dzgF1npmoAviYmyqpq7ngQMmz6agAUxoFs8HgAila2FvoAfGouZhpaOsKW8Dbx5gGFqVi0khR2CQCUeQWBZmDCtPDlqkmFRWpQWHhYACrWAA7wdvbiMtNOQ0U4tLDzVHjT3gD0exB4ODzwbMJY09MIwtJge3UNFCudRaPjdsBqcrRgdpraWBlLLoDTwKAQLDzMA4NgQSQANWg8AI9mCqyCLVWwjwFHkCXeWHaXwBpTcnjiBkJPTOOFgeDimMKTJ4YVi6mieAQ8WSZgAbhB4AB3ZptPT5MAJewUABMTgcEAmJzOagAyvxrhV7FjAiFWTxwuoWDwoAAxAi-HmFAXC0XtSX2YTTdbwAC0TAtYHlqwdEB4zrwTpdrr9AddtAIJ20UHlvOGahkofw-2EQqOFAAgng6FK+VhYAx5VEYiphKkMlkWqDVvz8wx-iUgeVKpiAsMHQAjfCEHhB3qurvZmSxhMG2Dwjx2YuxMvweqNYKg+yqudPbWrHVmPVslTqPFYbS0ABKBCF8Va7UKDro8s4HWGnHsE1o7g88vsGdo0VU74ACrR4XgexfGEMBLgSCh7SlXF5QoFo2kKXwdR3CJyQ8E8hUpb4XwpS9AjQ84wOmBI0Kg+wb1BTgfWgmNQV9MAyFjNgGjsNCLi-IULQ8ABVDYAEYAAYBNbbDXxxHCPAAOX4eAq2o8jaNEzx2O-PBpIEOTXmvRS2LQ-9AM3NQkOQg12SUrwABkIAiAw4xtEVEjFfJ5PGDsbmdftXJuAjxx-atXi6aD90Uu9goqDCLyQtt42vDstGsW9zIwtgElJIECLaJCN2ZUJTN3NRFWVLC40THgjjtcVDHvIpp1LctMgqawpSPCc1AzVQEASloAG5Vlq85HkaVpmRqQJ7IqiUpQhPkXnbEijgQTS5uNM1PSWopJQIqzVEMsxDO3Hhuk0E48AJAhJBwARZGEOKoGsUFCtONgepMEBMFSBBJGiWJFBQAB2JAZRlEAgnQXgZMUW42AkJQZDkBQhHE182F89QSXqMg-VdQhpjsGV4DAbr0V7Dy3UHHsqrA2hMZ4V0ECYPA7D4gmib1WUqrkAAPPBXXzcgeDsSR5B+PUIAYymMaxgDKEZtRmcJtQmFgAgxjsem8FZ16gn8EBxx4LwuHBgRFEgXEANgN6QHWC2hG2XYkAOE5pg8MhbgIe5TYoc3LbwGZBBANhJAA6ZqFBo3-c983XVUXp+Et63FDt-Y9idl23Y99Mo5jucwB9v3FED4PQ7BkA+GNoRSckaH442RPs3tx3-TTu49kr6vMF92YC99hAQd8IIgA) lacks a scrollbars in the .JS file. Did I do something wrong?

**Comment by porsager** [comment]
@tormodvm If you're not on Firefox 60 yet that's the reason.. They didn't enable esm modules in firefox before 60 ;)

**Comment by porsager** [comment]
@mike-ward It's actually on flems.io that I don't force `autoHeight` to be false.. You can set it to false, but I'll also fix it on flems.io right away..

**Comment by mike-ward** [comment]
Of course. I had `autoheight` on when I was displaying inline.

**Comment by porsager** [comment]
It's also fixed on flems.io now, so it'll be ignored unless it's iframed ;)

**Comment by tormodvm** [comment]
@porsager Updating to Firefox 60 did the trick. Thanks! :)

**Comment by porsager** [comment]
@mike-ward re
> I find the page jumps around sometimes when rendering. See http://mike-ward.net/2018/05/09/mithril-rising/. I ended up adding a scroll(0,0) to force it to the top. Seems to have something to do with the AJAX call in the last example.

I found out the issue was due to a hack inside codemirror. I've prevented codemirror from scrolling the window now, so you shouldn't see this issue any more.. Sorry about that!
