### ISSUE TITLE
some way of recovering from infinite loops

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems#55]
jsbin has this: https://github.com/jsbin/loop-protect (might be a bit heavy handed for flems)

I think at least it would be nice to have a way to stop the code from auto running _after_ getting into the infinite loop situation (url param maybe if UI method is not possible?).

As it is now it is not possible to recover even if you manually edit the json and add `{ autoReload: false }` because the initial load still triggers the infinite loop.

**Comment by fuzetsu** [comment]
Ah, didn't see this was already reported on https://github.com/porsager/flems.io/issues/7

Is this issue specific to flems.io, depending on the solution it could benefit the embedded flems as well no?

**Comment by porsager** [comment]
Yeah, it would be neat to have in flems core, but it would mean depending on babel which I'd like to avoid.

Perhaps some crazy regex'ing could handle adding some loop protection as well, but I'm not sure I'll have time to play around with that any time soon.. 

The solution for flems.io should be ready soon though, and I think that would be a fine solution for most cases.

**Comment by colshacol** [comment]
I've been working on a client-side sandboxing app for a while now, but it is such a mystery how to safely sandbox this crap. -_-

That said, I found this thread in my nightly search for sandboxing options/influences.

For my app (which currently does work, although sandboxes client-written code in a Node VM), I first compile the code with Babel. -- To make sure we don't get locked down by any infinite loops, I wrote a tiny Babel plugin, [found here](https://github.com/colshacol/bytesize/blob/master/server/sandbox/loopControl.js).

If you're willing to run your code through Babel first, this plugin has worked perfectly for me. (But don't ask me how it works. I wrote that crap 3 months ago...)

**Comment by tormodvm** [comment]
Could a "dontRunJs" flag in the URL be an alternative? I have students every week that gets something wrong in a for loop that freezes everything.

**Comment by porsager** [comment]
Toggling autorun state will be saved in the url, so could this do ? https://flems.io/#0=N4IghgrgLg9gSgUwDYzAExALgGZiQZwQF8g

**Comment by porsager** [comment]
Hi @colshacol .. thanks for your response, I'm sorry I've overlooked it.
I'm not really keen on forcing too much bable, but yes that could be a way to do it.

I'd rather finish up the flems.io fix mentioned above which is waaay overdue :-(

**Comment by porsager** [comment]
This has finally been implemented for flems.io.

Browsers handle things a bit differently. 

- Safari gets back simply by placing the cursor in the address bar and pressing enter. 

- Chrome on the other hand doesn't respond to reload or anything, so the quickest way is copying the url and open the flems in a new tab :-/

- Firefox the same

I'm surprised it's only safari which kills whatever runs when you reload or press enter in address bar.. Oh well.. At least it's a lot easier getting back before the endless loop right now ;)
