### ISSUE TITLE
console.log() %c handling

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems#58]
The following syntax for `console.log` works in the Chrome console, but not in flems:
```js
console.log('%cI am orange', 'color:orange', 'I am not');
```
[The current logic](https://github.com/porsager/flems/blob/b9d5aea/src/console/index.js#L89) will only deal with the formatted part of the log and ignore the rest.

The behaviour seems to vary by browser, but they do seem to consistently output all the arguments from `console.log` regardless of how they handle the css. 

I personally like how chrome handles it.

**Comment by porsager** [comment]
Not the prettiest fix, but the output is prettier now ;) Thanks @fuzetsu
