### ISSUE TITLE
Freezes in typescript mode when typing "for"

### ISSUE THREAD

**Issue by richyliu** [porsager/flems#60]
Flems freezes and becomes unresponsive when the word `for` is typed in typescript mode.

## To reproduce this bug:
1. Go to [flems.io](https://flems.io/)
2. Open the menu and select "typescript" as the transpile option
3. Go to the .ts tab
4. Type the word `for`

**Comment by porsager** [comment]
aww.. 
Apparently the typescript compiler thinks it should compile
```
for
```
to 
```
for (; ; )
  ;
```
https://www.typescriptlang.org/play/index.html#src=for

**Comment by porsager** [comment]
I've implemented a better way to recover from for loops now https://github.com/porsager/flems.io/issues/7#issuecomment-449870426 .

To avoid the lockup you can disable auto reload while writing the for loop.
