### ISSUE TITLE
ESM is incompatible with UI import feature

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#61]
[As we can see here](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIAW94AcyoHoCBXAOxwGsBzAOlgHsBbAnAQ3lgwEtSL6ABACw0AjDQAMBLo0bF4rAEYwajAFZgQAGhAAzLjA2oA2qFKtGENCBpZGULSAalEzqyAC+m0+cvoa6hycXeCtpHHoAJ3gAAgB5aJ0IpmiAchopGTlFZTUwFIAdUkKnMHplKHoqAApYquBIGARkVGjgJCYW9thiC2caBXokAE93T1bC6OiGuEQkFtrgCcno9sZ5qrKkABFkgF4APhX6bt74fsGhgEpNJfdrwrvLwuL6UlLyypq66aa51tWWqRiFAoKNNONSJMfrN1otIcsAXENlBtntDl0ehA+gNhvd4XcbqRHg5oVxXoYQOJUCIAGweLwgMwWKx0MAabRBLEhdAeAC62igPAohhMjJ8oUy8iUEBUAW0xAi9nQWFw+CIZEotAYzDYHG4vAEwjEkmksilOTlIHgQxwvnAsAiXBwIXcvPcQA), ESM seems to be incompatible with UI import feature: 
```
Unexpected token export
```
This breaks the import-and-edit feature, which is good for bug fix demos etc

**Comment by porsager** [comment]
I'm closing this out unless you have anything to add @barneycarroll ?
