### ISSUE TITLE
Files with .mjs extensions can't be imported from

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#62]
[If I use `.js`, I can import from it](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJABwwBcBjACwjQGsB7AegiywFciMAjWAOgCsEAaECRpoiMUXhgAPfDQBORAAQATGGAzMoSsMzQkiEEYoDyACgz9F7AJSLgAHTSLFEMIvNyA5sxyi4XWDRPIjJFAF4wxQBGWwcnZxc3UxCIOBc0ODY9GBo3Y1sU-wx8fCgAT3DFIjL8HLcMcMiAch09AxEmxQB+RQbERVb9QydTGztHBIS5GCJmOSczdkUAQki0TShuq0V+4ABfSwxrAG4JhL3jxRgoOBhFadn5xTQYAHcTcxOzvaubu9d3A0Is8NrYHnMnBgvD5xER-IFgqEAHyKABMW2MXBIGCgUC4xVKZVMxkO0N8cNs-XYx2ut3G8WcQMUwnwRKOpzQZ2cYHk7gAblCXJUopcIIoADy9Mmw+HiRGigDUCssS0iUO85LgyAgAF1bFyEjy5PzBVQYBVKFZ9QzJol3OwuGQMHBjK80AAFOQ0WoKIlmsrWa224NWZD+nWNEyKA3BnoxkOqWBiXph80R+OTfoZ20YVNlCORdh5iOUTIYbK5KPZ5xxm0h0Ph-ElcrmYtB+s7asJIvhjkG8FPDAc5x7RyjzloQbtJwsolSWJnAXGiprN6KKRYkSZOTMfTyUxfCfc3mmJeKABe6XXtgBpg3Tpdbs93pgvtM58DijKyHPBfXP51Pt4gHJwyg5PYQEEW5YCGLc8AAZiiRAohAA50GwXBEBAXgBCEEQxAkLDGFkBQozAL0sEUJouDoQhSAoah6EYFg2E4GAmkcRxhAyGhuCgGhPGJUxgGgmB9BgZRdmUGgsH6aSSBhUQuHYGhlDKPYDnpZxRPEySPjiSZpNkj5eOUAARGTwhReTFKIZTVIDfhvmsJy0D2QNOL0LdeJgAIBKEkTrjEsQ9OAIz+nWXENMsAzFB0kL+jMWLnHCkyoHMyywmsmgFPJey1Jc5zXPc6xIJAeLhgQLCAAZEHggA2VCdT2IA), but [If I use `.mjs`, I can't](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJABwwBcBjACwjQGsB7AegiywFciMAjWAOiwCsEANCBI00RGGLwwAHvhoAnIgAIAJjDAZmUZWGZoSRCKKUB5ABQYBS9gEolwADpolSiGCUX5Ac2Y4xcLlg0LyIyJQBecKUARjtHZxdXdzNQiDhXNDg2fRgadxM7VICMfHwoAE8IpSJy-Fz3DAiogHJdfUNRZqUAfiVGxCU2gyNnM1t7J0TE+RgiZnlnc3YlAEIotC0oHuslAeAAXysMGwBuScT9k6UYKDgYJRm5haU0GAB3UwtT8-3r2-u3B5GpEXps7I95s4MN5fBIiAEgiEwgA+JQAJm2Ji4JAwUCgXBKZXKZhMRxhfnhdgG7BONzuEwSLmBShE+GJxzOaHOLjACg8ADdoa4qtErhAlAAePrkuEIiRIsUAakVVmWUWhPgpcGQEAAunZuYlefIBUKqDBKpRrAbGVMkh52FwyBg4CY3mgAAryGh1RTE83lGw2u0h6zIAO6pqmJSGkO9WOhtSwcR9cMWyMJqYDTN2jBp8qRqLsfORyhZDA5PLRnMueO20NhiME0oVCwl4MN3Y1xLFiOcw0Q54YTkufZOMdctBDDrOVnE6Rxc6Ck2VdbvJTSbGiLLyZgGBRmb6Tnl8szLpQALwyG7sgLMm+drvdXp9MD9ZgvQaU5WQF8LG9-XV+wSQdnHKTl9hAIQ7lgYZtzwAAGRAEIAWgAZmiRBohAQ50GwXBEBALh+Cg4RRHESRCMYORFGjMBvSwJRmi4OhCFIChqHoRgWDYTgYGaJwnBETIaG4KAaC8EkzGAGCYAMGAVD2FQaCwAZlJIWExC4dgaBUcp9kOBkXFk+TFM+eIpmU1TPlElQABEVIiVF1M0ohtN0wMBB+GwvLQfYg0E-Rt1EmBAgkqSZJuOTxDM4ArIGDY8QMqwLKUEyYoGcxUpceKbKgezHPCZyaA0il3L0nzvN8-ybFI9KRgQQikLRAA2HDdX2IA).

**Comment by porsager** [comment]
I've been on the fence about supporting mjs, but I guess it might even solve the case of knowing if it's a module without content parsing. 

What do you think?
