### ISSUE TITLE
How do I enable "FULLSCREEN PREVIEW" in the toolbar?

### ISSUE THREAD

**Issue by starpause** [porsager/flems#63]
From my digging I don't see this feature in the source, but maybe I'm missing something. 

I could see how this would only be a feature of the flems.io website but not the library, but I'd like to get it working in the library as the code I'll be hosting demos for is not public. 

Thanks!

**Comment by porsager** [comment]
Hi.

Yeah, that's only on flems.io currently, but there's been some discussion about adding a similar feature to core here: https://github.com/porsager/flems/issues/27#issuecomment-362934448

I'm unfortunately pressed for time, and I don't think I'll be able to work on this for the next couple of months, but PRs are welcome ;)

**Comment by porsager** [comment]
Oh btw, since all the state for a flems is inside the link on flems.io, your code is as private as the people you share the code with. Nothing is sent to the server because the `#hash` part of a url is never sent over the wire ;)
