### ISSUE TITLE
Document hash format

### ISSUE THREAD

**Issue by isiahmeadows** [porsager/flems#65]
It'd be very valuable if you could document the hash format, particularly the important bits:

- The hash is of the format `#0=STR` where `STR` is the result of `LZString144.compressToEncodedURIComponent(JSON.stringify(state))` and `state` is as documented below.
- `state.files` - The array of user files, where each file an object `file` with the following properties:
	- `file.name` - The name of the file
	- `file.contents` - The contents of the file
	- `file.selections` - An optional comma-separated list of the following:
		- `L:C` - A single cursor
		- `L:C-L:C` - A full selection, where the first is the start and the second is the end of the selection.
		- Lines and columns are both 0-indexed.
- `state.links` - The array of external links, where each file an object `file` with the following properties:
	- `link.name` - The name of the link to display.
	- `link.url` - The resolved URL of the link in question.
	- `link.type` - The type of link. I know about `"script"`, but I know others exist.
	- `link.patches` - An optional list of patch arrays from a utility I can't remember off the top of my head.
	- `link.selections` - An optional comma-separated list of selections. Works the same way as `file.selections`.

**Comment by porsager** [comment]
Thanks @isiahmeadows 

It could be more complete, but I just c/p'ed yours here https://github.com/porsager/flems.io/blob/master/README.md ;)
