### ISSUE TITLE
How can I run flems.io locally?

### ISSUE THREAD

**Issue by aballeras01** [porsager/flems#66]
Hello,
I am a newbie and would like to find out how I can self-host flems.io?  I am learning as much as I can to web programming and this looks to be a very useful and helpful tool.

Thanks.

**Comment by osban** [comment]
Why would you want to self-host it?

**Comment by aballeras01** [comment]
For offline use and because the site is blocked from where I work.

**Comment by fuzetsu** [comment]
flems.io isn't open source so there isn't really a simple way to self host it I don't think.
https://github.com/porsager/flems.io

That said, flems.io is a wrapper around this package, flems, so you could create your own wrapper around it and host it yourself :thinking: 

The main things flems.io provides are the interface for adding dependencies / new files, which shouldn't be too hard to re-implement. 

[Here's a little demo I just coded up to give you an idea](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEGMAJw1QG0AGI2gXRIDMBLJGG0KTAW2RoAdAAsALn3jF0UMYlmoQAHjLk22MQAIY5MAF4AOiHFjcKAPTmWSPjCFsIVm3fGSjmsQE9siQyDkAHmLmAFaYAG6Yqupi7mAimOR4Yn4ArmIsALQAHEYAfErm0Rp50nhIYGIOsIq0KACctCAAvkQ8-IIgQiFcJJCy8mKKSFowYphymnqawAZQmprsnCia1HMLC7PzGwu8AisA5DjY3TAHROs7mv1ysocHlwvNl8yX8GxQANYwK9SMc88oP0xppMJUYFNNAAxZwACnwEDAqQEsiEACMIPhPERtOM5ABKOZzcwAKhJczJmgAggAZAAqmgA1JoAHKQzD4fCaKCIADuiw4iApJOp9KZmgA6pD8IgRohFojUnguUshVBKbSGcyACLszmaRBBRDkXjwbQUGKaWEQcjc7B8TTYMGfTAAc0QhPV5iJUF5HwRvKE0E+iE8Afm03lejyM0ubBYVsQQkw8DEAGlQ-jY9sFvHE0IQ54pnppgcoAcs1srtdoCC9lHHZQ+BpYQdBsaBUhuR0K48NmMJknVXZsEqRLDgN2BJpmp7qwO5EJyohKgRIfW+wswWI7MlYQuPZvNOREGJUibFim8H3mgb4HhNHnYUnC8XS7yK9nq0+AIT9djkHwraeBAqTaOe8ogWBvKYLIHgQJoMpyoc4oHkusornI+D4lmJ5niaR5ocOS7YO8YCIPueJDoKdjsFA+AAJL0YasIBFMMYBEI9Zvrig7oRUWE4Ue267qelGDnOVx4ee8wsFeao7LesoPk+L6hjxBz4J+VZXCMmjnma0zYE2LYHFS+oytgKxeD4mjvF8+nkGaNp2g6TpgC67pTogvY5hsv4GUIYhqEBOHHqeMlHgFTlLuM5A7hKbBiOOBwmNgFZZgZkKpWIpg-JYqRQNgnyukIkB8OYBzigZR7Alo9mfJCk5ZYC1YiUI7piDSHyfLCDX4kFIjyLCsJZtGX7Vrxi4NSOY59T1klteC6FiOJBJHrON6XICgJlBhlTVFwaAAIzHSgADMLRtCA9aKGVMC9DItxDGgIqThiASZDAbAAF4fK6KwYuQMrkJkH0zj6rjwDiGJYhNQ1sK64grMdtC0AApAA3JcfCJK6HwrLQ2PbEDIMo7Q2BsXA7xcqO5CkYgxPNHtAmHYo50oMdACsLSMM0QA)

There might some other considerations on the server side that I'm not thinking of, but it should be doable.

**Comment by starpause** [comment]
I don't know if this is the same question as @aballeras01 had or a new one. Some confusion with the naming but I think he and I are trying to do the same thing, create a stand alone playground that doesn't need to "dial home" to flems.io. 

For example, I noticed when I was trying to get a [stand alone, static web app version of flems running](https://github.com/porsager/flems/issues/64) that I still had to link back to flems.io:

`<script src="https://flems.io/flems.html" type="text/javascript" charset="utf-8"></script>`

Is the `flems.html` document that lives on the root at flems.io from this repository or modified specifically for flems.io? Is there a way to self host that file alongside local content or on a sever behind a firewall?

**Comment by porsager** [comment]
flems.html hosted on flems.io is the distributed version of this core library, so you can just download that or use the one found on this repo if you want to host it yourself 😉

**Comment by starpause** [comment]
Hi @porsager, thanks for the tip! I think making that relationship clear in the documentation would help future Flems-ers. 

Confirming that flems.html I got via `npm run build` does work stand alone! In the past I had trouble copying flems.html from flems.io so I was under the impression that file may have been modified from what this repo built. But if flems.io does simply host the latest flems.html then I must have been making some other mistake 🙃

**Comment by aballeras01** [comment]
Hello,
Did an npm run build but the flems.html created is not running.  There is an errant beginning comment "/*".  After removing it,  I just get a blank screen.  Also this link to flems.html is also not rendering.

https://flems.io/flems.html

Thanks.

**Comment by osban** [comment]
@aballeras01 I think you have to load the locally created `flems.html` in a `script` tag, as show in the docs/readme.

**Comment by kostasx** [comment]
Did you manage to make it work @aballeras01 ?

**Comment by porsager** [comment]
Hi @aballeras01 . If you're still having problems running flems yourself, feel free to open this issue again, but I'll close it out for now ;)
