### ISSUE TITLE
import/export issues

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems#67]
Found a couple little issues while writing code:
- [unable to use `$` as import alias](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEwOVjkY4cgCRzWcsNNrKA5FgjFC06AAE0MAB7EDlEHBixqxCPQQ8ADIgDMAOxsHCCYOHj41HACNPSMzDxsALqsQA)
- [unable to write bare export from statement](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4YADwAOtAE7EABMHkATGGAwBXKAoxx5Wea3lgZtAwHIsEYoRnQAAmgnFzlEHBixqxCPQQ8ABkQAFgBmNg4QTBw8fGo4ARp6RmYeNgBdViA)

**Comment by fuzetsu** [comment]
Found another parsing issue when an import statement spans multiple lines:

```js
// works fine
import { useEffect,  useReducer,   usePersist } from './hooks.js'

// breaks
import {
  useEffect,
  useReducer,
  usePersist
} from './hooks.js'
```
> Failed to resolve module specifier "./hooks.js". Invalid relative url or base scheme isn't hierarchical.

**Comment by porsager** [comment]
Thanks @fuzetsu ... The latest one you posted seems to work. Could you do a flems.io sample with the issue? [my try here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10RENtoDWcfACsEVOgybE8MAB4AHWgCdiAAklx1AVzgwAomDAxq6gLxqATAB008pao30ta3TABKMACbbqMZWoWAMy29irqmjp6AAr+cBAuFgAslCB6sKYQzniWiJYA7GwcIJg4eKLiNPSMzDwQWA7qwLZqrnqGxqYULW0e3r7+FGo9brHK8Vq2rGpgyrRYagDkAPR8gsJii7a2CgAUbh0mxENunj5+yicxcQnEAJSp6UdZaAg8AGyIQQCsRZxlPHw1DglUkNRkPDYAF1WEA)

**Comment by porsager** [comment]
Sorry this took so long, but both should work now. Unfortunately mithril has dropped esm support in the mean time, so you'll have to test with an esm compatible npm module...

**Comment by fuzetsu** [comment]
Sorry, I should have posted a flems example for the latest one I reported. I think I misinterpreted what was causing it to break, seems like it's a combination of things, probably messing with the regexes.

[Here is a repro](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDQGYCMAOAXQxADMBLOAUzGRVADsBDAW0uRADoALAF2cWIQY9HpRHsQAXwwMWbJCEoAPHgFoAJpQAOYDgCsag4aPELlWmFB4ACIfTA3WUAOaVrAXmvBJIYmEpUEDxkwjQKaEgATFhSMiBMrOxcMDAA1roGviB2JjzsAPQAVNbOcDAARoxwYNZaUJSMQQASKenWhfkAOvT5+dZkzBZWXtZOrtaS1iSwzNYA5Bz5ymqaOvpgc93d5pY2dg4jAK7+AEqU6ocQlFAY1seUAKIkJJRBt-cAyjyMou-+ALKUZgwP6UM4kUEAYSqcEqEFSEw8tXqjR4LTSYC29B2w32NnuAAVrmAyAdPAAKYDWVKUACet2+LkoPFuqzAt3IcFEUAmAEoPAA+Lzdax3fxPF5Bcnk-nuIXAEWi6xlCBVL6WRiuFA02kEJEAKQ+AHkAHIcBxQMj0ZxkEi08mc7nWAD8o2urnJjNcLKmFG5-KQ1i9zN5iuk1jZofokixOL2oXx-g+0HgcAAMgMyDYKVSrVmkQBWW5W7kANyqhduYkY5So6iRPCgh0ot2YjCUfMFwvoorx1hQcEzPv8PAzzCzes8n2+onJeZ4UcV9wA4mVKnAHqWxDxyYrRXNILAEHMMHvrDKuwqe0rewmg0j1DAIIdWCJzSmEFbnA8qK+eGfRVtc8eHfI84CaSgyGcXhrFUINQNTAAVGAtGsAAeawAHcrUfTCOCtbEoAgqCYOKLB+RHMcs3JQdxxsABqfoRGucs4CjG9pDPK8b1FdRSRrOtAwAQmrWtzmsAAfCTzzbDsADI5OVIdrCFWTeVPa8bx4LhYB4HgqEDHA0GMjSeIjbQwEDAch2LZioFYggzxja9F2veoeEOKAe2sujbkoodHOjWMlCGeN7ETShEJ0mA9KoJFyWYdkpnoVkLKRFACFleVFT7OBGAcaEECRe5wRlRV3M8nt7kK2FGlSXdNPPDhmsYFwwCy7szKA8kABEfkoDh6BgTCLzgvKCphDhnygeoRHQ0Z2usCqvIA5V8p4Gqps82bs2sPrREG4aysa0USHoclmo4VrnHapzTKVFBEtuS62UC0Uo2c7YQt2Ww73uHrKHKGBDnoK54qe5LUp0dLMsvHK7zIesp1OSgSGO0Vlqq-warheqzwulq2o67ieIgKhWsQgZKGBndEa2mbt3Yni6emnakRHSnWBph0UoW57CZupnRU4xrHqSl6LLe6wPuC0LfvCsVKFXCoqk3bd4sVHhaS0FtFS4Rh6HUKgbkVKk+LAATzlSoGQauQN1HKBlotiyhAz0qGak8DKJm6Yn4YVzQbdB84ADEe2RygAaDq5yQd259cN42PaZvttN0-TQ-DxWovTqhPR9BOjeuZOsVFe4JVeHcLzlTqlW683LfUflMbPPszofcoXXM6PM+sN2bFdNOYoz9Qw776xC+Ns9sMN4arvUdQ1ZEDMHDEa5PW1ltkqFpbmUq88Opn3COHqYEtyX0dSRMdetZ1jl6CZ8MUFvreG7E9RWUdoMfQlnRMu6ZyWR-CBGCKEdgeAkBGViLIRICh1hZByNuAoxRSgq2qMiBoQR2hdHoAMOWVIlzimeJXe6JVziXGuAAqYMx5iLGSBidYmx6BAICJXEI9h2AFiQGgaB8Q5DsCmmAQw2RjBIIUFIIgIBBz0HSLQGB8gQB1EwSBF86h4HEE8ogBQvAeA6CQL0CA6h6DrE0IOUsUBBrMnyPQLQzB8hKNRAAAWxCofI5seD2JREEDgqj1EgBfuwQ8ZAtB5GkPIpIrRdC+MyBoqAWiQA6L0QYoxJiAhkHMZYjxNi7EOKCM45Y+R6HpDcVfQpkSfHMDUTE-xm9AnQGCaEggkggA)

Commenting out the single export in ext-deps seems to make the error go away for some reason, but also moving the hook imports into a single line (which is what I thought the issue originally was). 

Thanks @porsager :100:

**Comment by porsager** [comment]
Uh, that's interesting. Thanks ! I'll look into it.

**Comment by porsager** [comment]
Ah, this was great, I had a really bad implementation of my topological sorting of module load order (I was a bit eager at the time when I made it work). It's now much better, and also a fix to this issue ;) Thank you @fuzetsu

**Comment by fuzetsu** [comment]
Awesome, great work @porsager ! :tada:
