### ISSUE TITLE
The timeout feels a little fast for me when updating JS...

### ISSUE THREAD

**Issue by isiahmeadows** [porsager/flems#68]
The timeout feels rather snappy, but it's so snappy that when you're updating JS and pause even for half a second trying to recall a name, it ends up lagging a little while it updates the iframe. Also, the intermediate errors do get annoying very quickly and they can be a little jarring at times. Could the timeout debounces be adjusted from [400ms](https://github.com/porsager/flems/blob/master/src/actions.js#L342) to ~750ms or maybe even ~1000ms?

**Comment by porsager** [comment]
I think it's pretty ok, and haven't heard others found it too fast, but I've added an option to specify a different `autoReloadDelay` now 🙂
