### ISSUE TITLE
Change script mode to support jsx by default?

### ISSUE THREAD

**Issue by creatorrr** [porsager/flems#69]
Love the idea behind `flems` and it's simplicity. I have started using it to create all of my short lessons and coding katas. It would be fantastic if `flems` provided `jsx` support out of the box. I have a local fork where I have change the script mode to `jsx` instead. If you think this could be useful, I am happy to open a PR.

**Comment by porsager** [comment]
Thanks a lot 😊 Glad to hear you find it useful. 

It does support jsx out of the box if using Babel as compiler, and if you're using something else than react you can set it for eg. mithril with a pragma. `/* @jsx m */` [sample flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9ACoABAAF+ADylYpEsQB00GrPgBOTACYwdACn21qAVxwN8AI1r6AnhQ1SpAHkIBGAHyEYvO5i3j4aAJQalDS0WAAO0EZ4thi2MORUcGkw1MQQ9Ag8AAyIACxsHCCYOHj41HAC0cLMPGwAulRQEGgA1gWolVx4WBDEhDrQURY65DwkxLFwiGJiFmix3QDmtTFiw6PjUDJe+McAbLsjY9D4-FHEjrHcIHDU47GirK2sQA)

**Comment by creatorrr** [comment]
Oh shoot, sorry for the bother, haha. Thank you! Closing this issue. :)
