### ISSUE TITLE
TSX support

### ISSUE THREAD

**Issue by axyz** [porsager/flems#72]
I'm trying to run some jsx code in a typescript source.

while jsx is enabled in the compiler options here: https://github.com/porsager/flems/blob/master/src/compilers.js#L49

only the `.ts` extension is supported and unless the extension is `.tsx` the typescript compiler will not be able to parse the jsx syntax.

P.S. unrelated: why the compilers are loaded from a static url? can they be provided by unpkg as well and maybe this way allow to use specific versions of the compiler for example?

**Comment by porsager** [comment]
Hi. Sorry for the late reply, I've overlooked the issues here.

The reason unpkg is not used is simply because it was too unreliable :-(

I'll try to look into why jsx doesn't work as soon as possible.

**Comment by porsager** [comment]
I'll close this out as I can't replicate.. Let me know if there's still an issue ;)
