### ISSUE TITLE
Rendering and execution suspended when using a custom type for script elements.

### ISSUE THREAD

**Issue by pygy** [porsager/flems#74]
Add anything [between the quotes in `<script src=""></script>`](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACeAE8JEALwAdEGoB8ggPQjxUjQEZOkGAjK8q6AAypDAFhABfALpOgA) and watch the rounded square spin forever...

**Comment by porsager** [comment]
Thanks @pygy ;) I've fixed this and added support for type="module" in html too
