### ISSUE TITLE
CoffeeScript syntax highlighting is broken

### ISSUE THREAD

**Issue by isiahmeadows** [porsager/flems#76]
![flems-coffeescript-comment](https://user-images.githubusercontent.com/4483844/76721207-793c2d00-66fc-11ea-8a83-7a653cc29951.png)

[Here's a live Flems link the moment I took the screenshot.](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0sD2AzXEEIANCLgJYxhoDaoAdgIYC2R6GAFvM1CSDvUSC0IADxJyANwAE5JAF4AOv2yDG5ehABOygHyiA9BMm6+kGAnKrq6AAyoATLZABfYgxZtMOfIT4CheBEAYmlmaXlpLQgARwBXcmjpAHJmcngOLUpkxXpcgEEAB0KoclhGeCt6COlJcggAd1RpAApJemwkCABKaQBaXTCUwuTiFIAJaChsUdqOrqwOSiRovLWtbDjEMBqWxmLegdzpFINk5tWurWa2+Z7+3WOTof3CsfbOiAwK+C0wMeYLWSIzGyXG2FYyW6uSeyQMqEKjAA5hBzlEIPQrjcPl1Do9qs9wq93ndvvBfv8wkCQXNPmSKRhESjoWsTnCEciIPC5GjLtpsXc8U8TkTiiS6T8-gDqbMcV9JWAMHIWblmBgNlsvoVohQAB41ZI5NbTcqVVQ1JDYWBxViCDAo+AAURgtvgACEAJ4ASSQKQC6k0WiNao1iGkJoqVVBZzGoYgOyKJTKkdU-ghhUo2hEPgIRFI5jgZvoNhAAEYAOyoAAspdc7hATFYIiwYGopACGKC6FcAF1SKV6ABrGx0BueERpDJZKAAAQcGFsGCrfDiWl46C48EKYFQBgMcXohUHSKwEIMk8ylDnC6X5-Sl6gGDS9AwACs2yB4B7Cl4wLAsoUQQuD2LhAA)

**Comment by porsager** [comment]
Ah yes, coffeescript syntax highlighting isn't included for codemirror.. I'll get that added.
