### ISSUE TITLE
Outdated TS parser?

### ISSUE THREAD

**Issue by ArthurClemens** [porsager/flems#77]
I stumbled on an unexpected result:

```typescript
// ts
const list = [...Array(5)].map((_, i) => i)
// [,,,,]
```
After some digging I found out that this happens with TS compiler 3.5.1 or older, with tsconfig setting transpile to `es5`. It might be that flems.io has one of these older TS compilers.

**Comment by porsager** [comment]
Ah of course.. It was at v2.4.2, and updated to v3.8.3 now :)
