### ISSUE TITLE
How to enable the menu and other features

### ISSUE THREAD

**Issue by cbluth** [porsager/flems#89]
Hello!
flems is amazing, thanks for an amazing project.

i am a javascript noob and im trying to run this locally, and i want to enable the menu and other features.

here is my `index.html`:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Flems</title>
  <meta charset="utf8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<style>
html {
    height: 100%;
    width: 100%;
    margin: 0;
}
body {
    display: block;
    min-height: 100%;
    width: 100%;
    height: 100%;
    margin: 0;
}
</style>
</head>
<body>
<script src="/flems.js" type="text/javascript" charset="utf-8"></script>
<script>
Flems(document.body, {
    files: [
      {
        name: 'index.html'
      }
   ]
})
</script>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/6709636/94399553-de6ee180-0167-11eb-8109-832095697a8c.png)

 

how can i enable the menu?

**Comment by porsager** [comment]
Hi.. Thanks a lot for the kind words.

That menu is not a part of flems core, it's a part of https://flems.io which uses this library, so you would have to implement a similar feature yourself if you need it.
