### ISSUE TITLE
Feature request: support SVG files through service workers

### ISSUE THREAD

**Issue by pygy** [porsager/flems#9]
I would have liked to write a repro for https://github.com/MithrilJS/mithril.js/issues/2014 but the SVG `<use>` tag has same origin policy restrictions that make it currently impossible.

It would be nice to be able to add new SVG files (like new \*Script/CSS ones) and have their content served through a service worker to the sandbox.

I've worked around the problem by using a gist and https://bl.ocks.org, but the workflow is obviously more choppy. OTOH I don't know when I'll need that functionality again, so there's no hurry as far as I'm concerned.

**Comment by porsager** [comment]
Could you post a flems with an example for this behavior (the same origin policy restrictions)?

From a usability viewpoint, wouldn't it be a little weird to add svgs together with scripts and styles?

**Comment by pygy** [comment]
[Here's an example](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8AQiTcEATwAOEAATsoAPgA6dANSD4ZeDEWIw8QQHotOiCrqrBWACyKGYWWABuAcyMBXSKmO2Lgl1dZAHcyJHgsAF5lEABGAFYABhj5CDJXHGiQACZE5JBZAA98OjAsnHgpVCMjYLqMYIBmDG4AJ3dcvKNAmItZWQD4CV1Vfv6MWCgHMABBWWBR2XIoKFRZVuQAbkX+gF9F4wNh81kDpAgSMD6xwSCwrIAFNvhenZvYMlbJuSOYLOXVrIyHQsBBWtptgVWllYvkjNd+sZXNdjOdLn0DohCvBZBIYfFegAjKawADWxix8BRXjkhSySRSeJisJSWA2JCyAGInq0XgV4ZiINjcVlGgSQIoNkgKUKqQcaUV6fkRTFGsq2RcuTy+bJJtMsnqwLMYgK6IjKSqQPFxYpXBsIHQZdjqZBFTEGQUmSA8qz2eV4JUwNUjLAkHQMK0GMFXNoJtxcEYAFakqRYKDdNwAWjAUnBiCMNiQhMaJEaEEaNgAHGKAJyJADsjVilaQjUrEGLDFD2VblZs2XrsHisViSBsJggBiM5GxHg2GfcObzEFqEAYETB2bcGB6IFNhzc-kJrX8flOZtkM0cZFwrjWViMfisZBvQTAX39geDofDkejsZ4BNk1TdNAmzXNtBXQti1Lcsq1rBsmxbNsO0aLskB7Nt+0HYdR3HfR4GnMhZ3nQJugg-NgjXDdWi3VwdzcFJQnCKJmR9ApQXSTI2PyVR4X6EBdkIegmBYdAMETKhiB4PgHXgVhBOEkBGGYVgJiNTgZP4eT0EEgBdXYgA).

Chrome sometimes gives same origin policy errors in the network tab, but I can't get it to work reliably. If you fix the last `<iimg>` tag to `<img>` the image loads fine. I'm a n00b at SVG but AFAICT documents imported with the `use` tag can probably rune their scripts in ways that could be dangerous, hence the restriction.

You could allow arbitrary files to be loaded and accessed at the root (maybe an extension => MIME types table would be needed?), and keep the `/api/` path for the REM-like service...

**Comment by porsager** [comment]
Ah, I get the idea of adding it as a resource now. So to avoid the same origin restrictions flems could fetch it and insert into the DOM [like this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHjgDcBzAAgHcIAJsUIBeADogAjAFYADBO6EYETiXEgATLPkhuADzJo46ksQAOiAPSXet-LwDM+WgCdOlrdssdOEgHxiaNzcLACucDD66nIKAJ7qOoouMGDqAMS8MBjCMC4AtNSwGC4SlgFoLN5cIAC+FOjYuIgEAFYIVHQMTMR4YDDE1IQAFADkpmZwVpbUAmj4Lhi8nBDE+HRYli0A1maEUFWceXBmLiswlgAsAgBGDmAOMA4XABwO0gCcsgDsDpLPAg5njBbhgZhoAc8LhovtRpJJJAILpZGHBiJZIHpiKFkgdvCczjYsjl8j58D4RgBKQLBfA5NBDZJwbgiPzcRm0mCYoYUqlBbi0pT0nzM1nAanBbgCWjUUI4BhELICfAQNBoXIACQAKgBZAAy3AA1CJuD5xTVecFavUQJgcHg1nB2jR6IxmM1agBdGpAA) ?

Thereby enabling `use` usage ?

**Comment by porsager** [comment]
@pygy Do you think it'd be worth adding a feature like the above? (even though it doesn't / won't work in safari) Since the workaround is so small I think it might be better to just let it be up to the user?

**Comment by pygy** [comment]
@porsager I had missed your initial reply... Yes, the workaround is fine I didn't know you could use the HTML document to look for sprites.
