### ISSUE TITLE
Remove Babel auto-switch

### ISSUE THREAD

**Issue by barneycarroll** [porsager/flems#99]
AFAICT Flems automatically switches js files to Babel transpilation if it encounters a parse error (assuming new language feature?). The feature trigger is misguided – casually typing out Javascript with constant evaluation is bound to generate plenty of parse errors – but also the Babel config shipped is less featured than current Chrome, so I typically end up with `regeneratorRuntime is not defined` if I'm using `await` or generators, even though the browser I'm using supports these natively.

**Comment by porsager** [comment]
Yeah, this has annoyed and confused me quite some times now as well. Let's get rid of that automagically bablification!
